config/routes.rb
Tasks::Application.routes.draw do
  
  match 'public_lists' => 'public_list#index'

  match 'favorite'       => 'favorite_list#create', via: :post
  match 'unfavorite'     => 'favorite_list#update', via: :put
  match 'favorite_lists' => 'favorite_list#index'

  resources :lists do
    resources :tasks
  end

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  authenticated :user do
    root to: 'lists#index'
  end

  devise_for :users

  root :to => "home#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :create], List
    can [:update, :destroy], List do |list|
      list.user.id.eql? user.id
    end
    
    can [:read, :create], Task
    can [:update, :destroy], Task do |task|
      task.list.user.id.eql? user.id
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :limited, :tasks_attributes
  
  belongs_to :user
  
  has_many :tasks, :dependent => :destroy
  
  validates :user, :name, :presence => true
  
  validates_inclusion_of :limited, :in => [true, false]
  
  accepts_nested_attributes_for :tasks, :reject_if => lambda { |t| t[:name].blank? }, allow_destroy: true
  
  def self.publics_for(user)
    where{ ( user_id.not_eq my{ user.id } ) & ( limited.eq false ) }
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name
  
  belongs_to :list
  
  validates :list, :name, :presence => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :login, :username
  # attr_accessible :title, :body
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  
  validates :first_name, :last_name,
            :presence => true,
            :length => { :within => 2..20 },
            :allow_blank => true
  
  validates :username,
            :presence => true,
            :length => { :within => 5..20 },
            :uniqueness => { :case_sensitive => false },
            :format => /^[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*$/,
            :allow_blank => true
  
  has_many :lists
  
  has_and_belongs_to_many :favorite_lists, 
                          :class_name  => "List",
                          :foreign_key => "user_id",
                          :join_table  => "lists_users", 
                          :uniq        => :true,
                          :before_add  => :before_adding_list
  
  protected
  
  def before_adding_list(list)
    raise "Only must add a list unlimited" if list.limited?
    raise "Only must add a list from other user" if list.user.eql?(self)
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  respond_to :html, :json
  responders :flash
end

app/controllers/favorite_list_controller.rb
class FavoriteListController < ApplicationController
  layout 'logged'
  
  before_filter :authenticate_user!
  
  def index
    @lists = current_user.favorite_lists
    respond_with(@lists)
  end
  
  def create
    @list = List.find(params[:list_id])
    current_user.favorite_lists << @list
    current_user.save
    respond_with(@list)
  end
  
  def update
    @list = List.find(params[:list_id])
    current_user.favorite_lists.destroy(@list)
    respond_with(@list)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  layout 'logged'
  
  before_filter :authenticate_user!
  
  load_and_authorize_resource :list
  
  def index
    @lists = current_user.lists
    respond_with(@lists)
  end

  def show
    @list = List.find(params[:id])
    respond_with(@list)
  end

  def new
    @list = List.new
    respond_with(@list)
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(params[:list])
    @list.user = current_user
    @list.save
    respond_with(@list)
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes(params[:list])
    respond_with(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    respond_with(@list)
  end
end

app/controllers/public_list_controller.rb
class PublicListController < ApplicationController
  layout 'logged'
  
  before_filter :authenticate_user!
  
  def index
    @lists = List.publics_for( current_user )
    respond_with(@lists)
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout 'logged'
  
  before_filter :authenticate_user!
  
  load_and_authorize_resource :task

  def index
    @tasks = Task.all
    respond_with(@tasks)
  end

  def show
    @task = Task.find(params[:id])
    respond_with(@task.list, @task)
  end

  def new
    @task = Task.new
    respond_with(@task.list, @task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @list = List.find(params[:list_id])
    @task.list = @list
    @task.save
    respond_with(@list, @task)
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(params[:task])
    respond_with(@task.list, @task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_with(@task.list, @task)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def navigation_links
    links = []
    
    options = params[:controller] == "lists" ? { class: "active" } : {}
    links << content_tag(:li, link_to("My Lists", lists_path), options).html_safe
    
    options = params[:controller] == "public_list" ? { class: "active" } : {}
    links << content_tag(:li, link_to("Public Lists", public_lists_path), options).html_safe
    
    options = params[:controller] == "favorite_list" ? { class: "active" } : {}
    links << content_tag(:li, link_to("Favorite Lists", favorite_lists_path), options).html_safe

    content_tag(:ul, links.join("\n").html_safe, class: "nav")
  end  
end

app/helpers/favorite_list_helper.rb
module FavoriteListHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/public_list_helper.rb
module PublicListHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/favorite_list/index.html.erb
<% content_for :subtitle do %>
  <h1>Favorite lists</h1>
<% end %>

<table id="my_lists">
  <tr>
    <th>User</th>
    <th>List name</th>
    <th colspan="3"></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td width="40%"><%= list.user.username %></td>
    <td width="50%"><%= list.name %></td>
    <td><%= link_to 'Unfavorite', list, id: 'unfavorite', class: 'btn danger' %></td>
  </tr>
<% end %>
</table>

app/views/home/index.html.erb
<%= simple_form_for(resource, 
                    :as => resource_name, 
                    :wrapper => :login, 
                    :url => session_path(resource_name) ) do |f| %>

	<%= f.input :login, :required => true, :autofocus => true, :label => false, :placeholder => 'Login' %>
	<%= f.input :password, :required => true, :label => false, :placeholder => 'Password' %>
    <%= f.button :submit, "Sign in", :class => "btn primary" %>
<% end %>

<%= render "devise/shared/links" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
	<meta charset="utf-8" />
	<title>Tasks</title>
	<%= stylesheet_link_tag "bootstrap.min" %>
	<%= csrf_meta_tags %>
	<style type="text/css">
	  /* Override some defaults */
	  html, body {
	    background-color: #eee;
	  }
	  
	  body {
	    padding-top: 40px; 
	  }
	  
	  .container {
	    width: 300px;
	  }

	  /* The white background content wrapper */
	  .container > .content {
	    background-color: #fff;
	    padding: 20px;
	    margin: 0 -20px; 
	    -webkit-border-radius: 10px 10px 10px 10px;
	       -moz-border-radius: 10px 10px 10px 10px;
	            border-radius: 10px 10px 10px 10px;
	       -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
	          -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
	               box-shadow: 0 1px 2px rgba(0,0,0,.15);
	  }

	  .login-form {
	    margin-left: 65px;
	  }

	  legend {
	    margin-right: -50px;
	    font-weight: bold;
	    color: #404040;
	  }

	</style>
  </head>
  <body>
	<div class="container">
		<div class="content">
			<div class="row">
				<div class="login-form">
					<h2>Login</h2>
					<%= yield %>
	        	</div>
	    	</div>
		</div>
	</div>
  </body>
</html>

app/views/layouts/logged.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <header class="master">
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <%= link_to "Tasks", root_path, :class => 'brand' %>
          <div class="nav-collapse">
	        <%= navigation_links %>
	      </div>
	      <% if current_user %>
	        <p class="pull-right">Logged as <%= current_user.first_name %> - <%= link_to "Logout", logout_path %></p>
	      <% end %>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <% if notice %>
      <div class="alert-message success fade in" data-alert="alert">
        <a class="close" href="#">×</a>
        <p><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert-message alert fade in" data-alert="alert">
        <a class="close" href="#">×</a>
        <p><%= alert %></p>
      </div>
    <% end %>
	
    <div class="row">
      <div class="span16">
        <%= yield :subtitle %>
      </div>
      <div class="span15">
        <%= yield %>
      </div>
    </div>
  </div>

  <%= javascript_include_tag "application" %> 
  <%= yield :javascript %>
  <%= yield :scripts %>
</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list, :wrapper => :inline, :html => { :class => 'form-horizontal' } ) do |f| %>
  <div class="inputs">
	<%= f.input :name, :autofocus => true %>
	<%= f.input :limited, as: :boolean %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn primary' %>
    <%= link_to 'Cancel', lists_path, :class => 'btn danger' %>
  </div>
<% end %>

app/views/lists/_task_fields.html.erb
<%= f.input :name, :label => 'Task' %>
<%= link_to_remove_fields image_tag('/assets/remove-action.png'), f %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<% content_for :subtitle do %>
  <h1>My lists</h1>
<% end %>

<table id="my_lists">
  <tr>
    <th colspan="3"><%= List.human_attribute_name(:name) %></th>
    <th><% if can? :create, List.new %><%= link_to image_tag('/assets/add-action.png'), new_list_path, title: 'New list', rel: 'New list' %><% end %></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td width="90%"><%= list.name %></td>
    <td><% if can? :read, list %><%= link_to 'Show', list, :class => 'btn' %><% end %></td>
    <td><% if can? :update, list %><%= link_to 'Edit', edit_list_path(list), :class => 'btn primary' %><% end %></td>
    <td><% if can? :destroy, list %><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn danger' %><% end %></td>
  </tr>
<% end %>
</table>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<p>
  <b>List Name:</b>
  <%= @list.name %>
</p>

<br />

<%= render :partial => 'tasks/index' %>

<% if can? :update, @list %><%= link_to 'Edit', edit_list_path(@list), :class => 'btn primary' %><% end %>
<%= link_to 'Back', lists_path, :class => 'btn' %>

app/views/public_list/index.html.erb
<% content_for :subtitle do %>
  <h1>Public lists</h1>
<% end %>

<table id="my_lists">
  <tr>
    <th>User</th>
    <th>List name</th>
    <th colspan="3"></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td width="40%"><%= list.user.username %></td>
    <td width="50%"><%= list.name %></td>
    <td>
      <% unless current_user.favorite_lists.exists? list %>
        <%= link_to 'Favorite', list, id: 'favorite', class: 'btn primary' %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/tasks/_form.html.erb
<%= simple_form_for([@list, @task], 
                    :id => 'new_task',
                    :wrapper => :inline, 
                    :html => { :class => 'form-horizontal' } ) do |f| %>

  <div class="inputs">
    <%= f.input :name, :label => 'Task name' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn primary' %>
  </div>
<% end %>

app/views/tasks/_index.html.erb
<table id="tasks">
  <tr>
    <th>Task Name</th>
    <th><% if can? :create, Task.new %><%= link_to image_tag('/assets/add-action.png'), list_path(@list), title: 'New task', rel: 'New task', id: 'new_task' %><% end %></th>
  </tr>

<% @list.tasks.each do |task| %>
  <tr>
    <td colspan="2"><%= task.name %></td>
  </tr>
<% end %>
</table>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>